### PR TITLE
@state doesn't exist, must be @_state (master branch)

### PR DESCRIPTION
**Pull request by michbeck100**
This hopefully fixes https://github.com/michbeck100/pimatic-hap/issues/37

### CODE REVIEW

**Comment by mwittig** [comment]
With which version did you test this and which error message did you get? Thanks

**Comment by michbeck100** [comment]
I didn't have to test this and I don't get an error, because the code runs just fine. It just doesn't work, because there is no global variable called @state. The only variable you can use is @_state. I came over this because of an issue with pimatic-hap and the Shellswitch. Then I looked at the sources and saw this.

**Comment by michbeck100** [comment]
In fact, a lot of issues people have with pimatic-hap are originated in the actual plugin that is triggered by pimatic-hap. In this case the Shellswitch executes twice.

**Comment by mwittig** [comment]
OK, thanks to the @ modifier there is no error message, but no doubt the code is wrong, from the beginnings, btw. I'll fix it on the v0.9.x branch.

**Comment by michbeck100** [comment]
is the master branch still active anyway? I guess you should switch master to v0.8.x and v0.9.x to master? i think this should be done with pimatic itself, too.

**Comment by mwittig** [comment]
Right. Either switch branches or possibly rebase master as it is not intended to do further releases von v0.8 anyway.

**Comment by mwittig** [comment]
Actually, your fix has revealed another bug - fixed with b26195eacfd0de0a0aea4bd2b9ff749959053438

**Comment by michbeck100** [comment]
You're not the only one. I have seen the exact same bug in another plugin already ;-)

**Pull request closed without merging**
